# Changing the Shape of a Tensor

## Reshaping a tensor

The `shape()` function allows us to create a tensor with the same data and number of original tensor elements.
- Requires two parameters. The first parameter input is the tensor the be reshaped. The second parameter is the `shape` which is a tuple of int, the new shape.
- **Note:** You can use `-1` as an argument for one dimension, which means you don't specify the size for this dimension. It would be inferred from the remaining dimensions.

### Task 1: Create a 1-D tensor with 8 elements and store it in the variable `a`.
### Task 2: Reshape `a` with a new shape of (2, 4). This  shaping is row-wise.
### Task 3: Use `-1` to reshape `a`. 
Specifically, use the shape (2, -1) for the new shape. This total element is 8, the first dimension is 2, so the second dimension could be inferred.

In [1]:
import torch

a = torch.arange(1, 9)
print("The original tensor:")
print(a, "\n")

b = torch.reshape(a, (2, 4))
print("The reshaped tensor with shape (2, 4):")
print(b, "\n")

c = torch.reshape(a, (2, -1))
print("The reshaped tensor with shape (2, -1):")
print(c, "\n")

The original tensor:
tensor([1, 2, 3, 4, 5, 6, 7, 8]) 

The reshaped tensor with shape (2, 4):
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]]) 

The reshaped tensor with shape (2, -1):
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]]) 



## Squeezing a Tensor

In [2]:
import torch

a = torch.ones((3, 1, 2))
print("The original shape of a is {}".format(a.shape))
print("The original a tensor is \n{}".format(a))

a = torch.squeeze(a, dim=1)
print("\nThe new shape of a is {}".format(a.shape))
print("The new a tensor is \n{}".format(a))

b = torch.ones((3, 1, 2, 2))
print("\nThe original shape of b is {}".format(b.shape))
print("The original b tensor is \n{}".format(b))

b = torch.squeeze(b)
print("\nThe new shape of b is {}".format(b.shape))
print("The new b tensor is \n{}".format(b))

The original shape of a is torch.Size([3, 1, 2])
The original a tensor is 
tensor([[[1., 1.]],

        [[1., 1.]],

        [[1., 1.]]])

The new shape of a is torch.Size([3, 2])
The new a tensor is 
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

The original shape of b is torch.Size([3, 1, 2, 2])
The original b tensor is 
tensor([[[[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]]]])

The new shape of b is torch.Size([3, 2, 2])
The new b tensor is 
tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])


## Un-squeezing a tensor

In [3]:
import torch

a = torch.ones((3, 3))
print("The original shape of a is {}".format(a.shape))
print("The original a tensor is \n{}".format(a))

a = torch.unsqueeze(a, dim=1)
print("\nThe new shape of a is {}".format(a.shape))
print("The new a tensor is \n{}".format(a))

The original shape of a is torch.Size([3, 3])
The original a tensor is 
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

The new shape of a is torch.Size([3, 1, 3])
The new a tensor is 
tensor([[[1., 1., 1.]],

        [[1., 1., 1.]],

        [[1., 1., 1.]]])


## Transposing a tensor

In [4]:
import torch

a = torch.ones((2, 4))
print("The original shape of a is {}".format(a.shape))
print("The original a tensor is \n{}".format(a))

a = torch.transpose(a, 0, 1)
print("\nThe new shape of a is {}".format(a.shape))
print("The new a tensor is \n{}".format(a))

b = torch.ones((2, 4, 2))
print("\nThe original shape of b is {}".format(b.shape))
print("The original b tensor is \n{}".format(b))

b = torch.transpose(b, 1, 2)
print("\nThe new shape of b is {}".format(b.shape))
print("The new b tensor is \n{}".format(b))

The original shape of a is torch.Size([2, 4])
The original a tensor is 
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

The new shape of a is torch.Size([4, 2])
The new a tensor is 
tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

The original shape of b is torch.Size([2, 4, 2])
The original b tensor is 
tensor([[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]])

The new shape of b is torch.Size([2, 2, 4])
The new b tensor is 
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
