# Concatenating Tensors

In [7]:
import  torch

a = torch.rand((3, 3))
print("The original tensor a is \n {}".format(a))
result = torch.cat((a, a), dim=0)
print("The shape of result is {}".format(result.shape))
print("The new tesnor is\n {}".format(result))

print()

b = torch.randn((3, 3))
print("The original tensor b is\n {}".format(b))
result = torch.cat((b, b), dim=1)
print("The shape of result is {}".format(result.shape))
print("The new tensor is\n {}".format(result))

The original tensor a is 
 tensor([[0.4662, 0.0997, 0.5191],
        [0.2157, 0.0764, 0.5140],
        [0.6489, 0.1500, 0.2382]])
The shape of result is torch.Size([6, 3])
The new tesnor is
 tensor([[0.4662, 0.0997, 0.5191],
        [0.2157, 0.0764, 0.5140],
        [0.6489, 0.1500, 0.2382],
        [0.4662, 0.0997, 0.5191],
        [0.2157, 0.0764, 0.5140],
        [0.6489, 0.1500, 0.2382]])

The original tensor b is
 tensor([[ 0.6761,  0.4923, -1.2221],
        [-0.2422,  1.6382,  0.5304],
        [-0.1059, -0.5245, -0.5382]])
The shape of result is torch.Size([3, 6])
The new tensor is
 tensor([[ 0.6761,  0.4923, -1.2221,  0.6761,  0.4923, -1.2221],
        [-0.2422,  1.6382,  0.5304, -0.2422,  1.6382,  0.5304],
        [-0.1059, -0.5245, -0.5382, -0.1059, -0.5245, -0.5382]])


## Stacking the Tensors

In [10]:
import torch
a = torch.randn((2, 2))
b = torch.randn((2, 2))
print("The original tensor a is\n {}".format(a))
print("The original tensor b is\n {}".format(b))
result = torch.stack((a, b), dim=1) # stack along the second dimension
print("The shape of result is {}".format(result.shape))
print("The new tensor is\n {}".format(result))

The original tensor a is
 tensor([[-1.7099,  0.2728],
        [-0.2311, -0.6671]])
The original tensor b is
 tensor([[-0.5565,  0.6501],
        [ 1.5452, -1.6176]])
The shape of result is torch.Size([2, 2, 2])
The new tensor is
 tensor([[[-1.7099,  0.2728],
         [-0.5565,  0.6501]],

        [[-0.2311, -0.6671],
         [ 1.5452, -1.6176]]])
