# Selecting Elements from a Tensor

## Selecting tensor with index

Example: Take a 2-dimensional tensor as an example. Consider the matrix.
- `tensor[2, 3]`: Get only one value.
- `tensor[:, 1]`: Get teh second column of the tensor.
- `tensor[1, :]`: Get the second row from the tensor. 

For higher-dimensional tensors, the operations are the same. Such as `tensor[:,2,:]`.

In [5]:
# Select element with [] operator
import torch

a = torch.arange(1, 10).reshape((3, 3))

print("The original teonsor")
print(a)

print("Select only one element")
print(a[1, 1])


The original teonsor
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Select only one element
tensor(5)


## Selecting tensor with `index_select`
`PyTorch` provides a function `index_select` which enables us to select some elements from a tensor with indices. 

At first, we need to create a tensor (`Long` type) that indicates the indices we want to select. 
- Since we want to use `index` to locate the element in the tensor, this tensor must be of `Long` type.

`index_select` requires the following parameters:
- The first parameter is the tensor we want to select. 
- `dim`: It indicates the dimension in which we index. In this example, the tensor is a 2-dimensional tensor.
    - `dim=0` means the row
    - `dim=1` means the column
- `index`: The 1-D tensor containing the indices to index.

### Task 1: Create a 2-D tensor and store it to `a`
### Task 2: Create a `Long` type tensor. 
This is a 1-D tensor containing the indices to the index.
### Task 3: Select tensor from `a` with specific index and dim.

In [10]:
import torch
a = torch.arange(1,10).reshape((3, 3))

indices = torch.LongTensor([0, 2])
print(indices)

result = torch.index_select(a, dim=0, index=indices)
print(result)

tensor([0, 2])
tensor([[1, 2, 3],
        [7, 8, 9]])


## Selecting tensor with a mask

The mask tensor is `BoolTensor`, which identifies which elements are chosen. 
- The shape of the mask tensor and the original tensor don't need to match, but they must be broadcastable.
- **Note:** In this notebook, we will only consider situations where the shape of the original tensor and mask are the same.

I.e., PyTorch enables us to pass a tensor of Boolean type to `masked_select`, which selectes desired elements from another tensor.
- The first parameter is the original tensor you want to select and the second is the mask tensor.
- **Note:** Unlike other functions, the result of `masked_select` is a one-dimensional vector.

In [13]:
import torch

a = torch.arange(1, 10).reshape((3, 3))

mask = torch.BoolTensor([[True, False, True],
                         [False, False, True],
                         [True, False, False]])

print("the mask tensor is: \n{}".format(mask))
print("The original tensor is: \n{}".format(a))
result = torch.masked_select(a, mask)
print("The result is {}".format(result))

the mask tensor is: 
tensor([[ True, False,  True],
        [False, False,  True],
        [ True, False, False]])
The original tensor is: 
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
The result is tensor([1, 3, 6, 7])
