# Tensor Metadata

## Getting type from `dtype`

The `dtype` attribute of a PyTorch tensor can be used to get its type information.

The code below creates a tensor with the float type and prints the type information.

In [1]:
import torch

a = torch.tensor([1, 2, 3], dtype=torch.float)
print(a.dtype)

torch.float32


## Getting size from `shape` and `size`
Note that...
- `shape` is an attribute
- `size()` is a function

In [2]:
a = torch.ones((3, 4))
print(a)
print(a.shape)
print(a.size())

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.Size([3, 4])
torch.Size([3, 4])


## Getting the number of dim
The number of dimensions of a PyTorch tensor can be obtained using the `ndim` attribute or using the `dim()` funtion, or its alias `ndimension()`.

In [3]:
a = torch.ones((3, 4))
print(a)
print(a.ndim)
print(a.dim())

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
2
2


## Getting the number of elements
Two ways to get the number of elements of a tensor, `nelement()` and `numel()`. Both of them are functions.

In [5]:
a = torch.ones((3, 4, 6))
print(a)
print(a.numel())

tensor([[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]])
72


## Checking if the tensor is on GPU
`is_cuda` is an attribute of a tensor.
- It is ture if the tensor is stored on the GPU.
- Otherwise it will false.

## Getting the device
`device` is an attribute of a tensor that contains the information of the device being used by the tensor.

In [6]:
a = torch.ones((3, 4, 6))
print(a.device)

cpu


In [8]:
import torch

a = torch.rand((2, 3, 4), dtype=torch.float)

print("The dtype of tensor a is {}.\n".format(a.dtype))

print("The size of tensor a is {}.".format(a.size()))
print("The shape of tensor a is {}.\n".format(a.shape))

print("The dims of tensor a is {}.".format(a.dim()))
print("The dims of tensor a is {}.\n".format(a.ndim))

The dtype of tensor a is torch.float32.

The size of tensor a is torch.Size([2, 3, 4]).
The shape of tensor a is torch.Size([2, 3, 4]).

The dims of tensor a is 3.
The dims of tensor a is 3.



## My questions ❓

1. What is the difference betwen the size and shape of a tensor?